export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RESULT = 'SEARCH_RESULT';
export const SEARCH_FAILURE = 'SEARCH_FAILURE'
export const CHANGE_FIELD = 'CHANGE_FIELD';

export const DETAIL_CHOICE = 'DETAIL_CHOICE';
export const DETAIL_REQUEST = 'DETAIL_REQUEST';
export const DETAIL_RESULT  = 'DETAIL_RESULT'
export const DETAIL_FAILURE = 'DETAIL_FAILURE';
